name: Run unit tests on PR
on: 
    workflow_dispatch:
jobs:
    run-tests-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: List content
              run: ls
            - name: Secret Scanning
              uses: trufflesecurity/trufflehog@main
              with:
                extra_args: --results=verified,unknown
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Run tests
              run: |
                cd server
                npm install
                # npm test
            